// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IoTAccessControl
 * @dev Smart Contract for recording and auditing adaptive access decisions
 *      for IoT devices in an AI-Driven Access Control System.
 *      Compatible with Remix IDE and EVM-compatible blockchains.
 */
contract IoTAccessControl {
    
    // Access Decision Enum
    enum Decision {
        DENY,           // 0: High Risk (Risk > 60)
        LIMITED,        // 1: Medium Risk (Risk 31-60)
        ALLOW           // 2: Low Risk (Risk 0-30)
    }

    // Access Log Struct
    struct AccessLog {
        uint256 id;
        string deviceId;
        string resource;
        uint256 riskScore;      // 0 - 100
        uint256 trustScore;     // 0 - 100
        Decision decision;      // ALLOW, LIMITED, DENY
        string reason;          // Explainable AI reason
        uint256 timestamp;      // Block timestamp
        address recordedBy;     // Gateway / Admin address
    }

    // Contract state variables
    address public owner;
    uint256 public logCounter;
    
    // Mapping from log ID to AccessLog
    mapping(uint256 => AccessLog) public accessLogs;
    
    // Device-specific log IDs mapping
    mapping(string => uint256[]) private deviceLogs;

    // Events for real-time monitoring and off-chain indexers
    event AccessRecorded(
        uint256 indexed id,
        string indexed deviceId,
        string resource,
        uint256 riskScore,
        uint256 trustScore,
        Decision decision,
        uint256 timestamp,
        address indexed recordedBy
    );

    event DeviceStatusAlert(
        string indexed deviceId,
        Decision decision,
        uint256 riskScore,
        string reason,
        uint256 timestamp
    );

    modifier onlyOwner() {
        require(msg.sender == owner, "Only authorized gateway/owner can execute");
        _;
    }

    constructor() {
        owner = msg.sender;
        logCounter = 0;
    }

    /**
     * @notice Records an access control decision made by the AI adaptive engine
     * @param _deviceId Unique identifier of the IoT device (e.g., CCTV_01)
     * @param _resource Resource requested (e.g., Security Camera, Door Lock)
     * @param _riskScore Calculated risk score (0-100)
     * @param _trustScore Evaluated device trust score (0-100)
     * @param _decision Decision enum (0=DENY, 1=LIMITED, 2=ALLOW)
     * @param _reason Explanation generated by the AI classifier
     */
    function recordAccess(
        string memory _deviceId,
        string memory _resource,
        uint256 _riskScore,
        uint256 _trustScore,
        Decision _decision,
        string memory _reason
    ) public returns (uint256) {
        require(_riskScore <= 100, "Risk score must be between 0 and 100");
        require(_trustScore <= 100, "Trust score must be between 0 and 100");

        logCounter++;
        uint256 currentId = logCounter;

        accessLogs[currentId] = AccessLog({
            id: currentId,
            deviceId: _deviceId,
            resource: _resource,
            riskScore: _riskScore,
            trustScore: _trustScore,
            decision: _decision,
            reason: _reason,
            timestamp: block.timestamp,
            recordedBy: msg.sender
        });

        deviceLogs[_deviceId].push(currentId);

        emit AccessRecorded(
            currentId,
            _deviceId,
            _resource,
            _riskScore,
            _trustScore,
            _decision,
            block.timestamp,
            msg.sender
        );

        // Emit alert if decision is DENY or LIMITED
        if (_decision == Decision.DENY || _decision == Decision.LIMITED) {
            emit DeviceStatusAlert(
                _deviceId,
                _decision,
                _riskScore,
                _reason,
                block.timestamp
            );
        }

        return currentId;
    }

    /**
     * @notice Retrieves an access log by its ID
     * @param _id ID of the access log
     */
    function getAccessLog(uint256 _id) external view returns (AccessLog memory) {
        require(_id > 0 && _id <= logCounter, "Log does not exist");
        return accessLogs[_id];
    }

    /**
     * @notice Returns total number of recorded access logs
     */
    function getAccessLogCount() external view returns (uint256) {
        return logCounter;
    }

    /**
     * @notice Returns all log IDs associated with a specific device
     * @param _deviceId Device identifier
     */
    function getDeviceLogs(string memory _deviceId) external view returns (uint256[] memory) {
        return deviceLogs[_deviceId];
    }

    /**
     * @notice Transfer contract ownership
     * @param _newOwner Address of new owner/gateway
     */
    function transferOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "Invalid new owner");
        owner = _newOwner;
    }
}
